<?php
echo "云签到软件完整名称：";
echo SYSTEM_FN;
echo "<br>";
echo "云签到软件版本：";
echo SYSTEM_VER;
echo "<br>";
echo "云签到软件根目录";
echo SYSTEM_ROOT;
echo "<br>";
echo "$_GET 的值，建议使用此常量表示当前插件的某个页面：";
echo SYSTEM_PAGE;
echo "<br>";
echo "站点地址，option::get的值：";
echo SYSTEM_URL;
echo "<br>";
echo "站点名称：";
echo SYSTEM_NAME;
echo "<br>";
echo "表示是否开启开发者模式，由options表的dev记录指示：";
echo SYSTEM_DEV;
echo "<br>";
echo "MySQL 数据库地址：";
echo DB_HOST;
echo "<br>";
echo "MySQL 数据库名称：";
echo DB_NAME;
echo "<br>";
echo "MySQL 数据库用户名：";
echo DB_USER;
echo "<br>";
echo "MySQL 数据库密码：";
echo DB_PASSWD;
echo "<br>";
echo "MySQL 数据库前缀：";
echo DB_PREFIX;
echo "<br>";
echo "用户组名称（英文）：";
echo ROLE;
echo "<br>";
echo "如果用户已经登录会被定义为true：";
echo LOGIN;
echo "<br>";
echo "仅用户登录后有效，当前用户的ID(UID)：";
echo UID;
echo "<br>";
echo "仅用户登录后有效，当前用户的邮箱：";
echo EMAIL;
echo "<br>";
echo "仅用户登录后有效，当前用户的用户名：";
echo NAME;
echo "<br>";
echo "表示是否为引擎环境，由options表的isapp记录指示：";
echo ISAPP;
echo "<br>";
echo "仅用户登录后有效，当前用户的贴吧数据所在表：";
echo TABLE;
echo "<br>";
echo "仅用户登录后有效，当前用户是不是VIP（管理员和vip成员都返回true）：";
echo ISVIP;
echo "<br>";
?>